version: "3.7"
services:
  db:
    image: postgres:11.6
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env.db.development
  server:
    build:
      context: ./server
    stdin_open: true
    tty: true
    volumes:
      - ./server/:/workspace/server
      - bundle:/bundle
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    env_file: .env.db.development
volumes:
  postgres-data:
  bundle:
