version: '3.7'
services:
  client:
    build:
      context: ./client
    tty: true
    volumes:
      - ./client/:/workspace/client
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    command: npm run start