version: '3.7'
services:
  server:
    build:
      context: ./server
      target: development
    tty: true
    volumes:
      - ./server/:/go/src/app/server
    ports:
      - "8080:8080"
    command: air