version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app
    tty: true
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
